# -*- coding: utf-8 -*-
"""PhisingWebsite-ID 327.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-EaDjTIs4FL2EaJx5AOKaUrfuWUHGOf

# Klasifikasi Phishing Website
**Dataset:** Phishing Websites (UCI ML Repository — ID: 327)  
**Model:** Random Forest (RF) | K-Nearest Neighbors (KNN) | Support Vector Machine (SVM)  | eXtreme Gradient Boosting (XGBOOST)

## 1. Import Library
"""

!pip install ucimlrepo imbalanced-learn

# INSTALLASI (Hanya perlu sekali)
!pip install ucimlrepo imbalanced-learn xgboost

# Library standar dan visualisasi
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# IMPORT XGBOOST SECARA LENGKAP
import xgboost as xgb
from xgboost import XGBClassifier

# Sumber dataset
from ucimlrepo import fetch_ucirepo

# Preprocessing dan splitting
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler

# Balancing data (SMOTE)
from imblearn.over_sampling import SMOTE

# Model klasifikasi
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

# Metrik evaluasi
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, roc_curve,
    confusion_matrix, classification_report
)

"""## 2. Load Dataset dari UCI ML Repository"""

# Mengambil dataset Phishing Websites langsung dari UCI ML Repository (ID: 327)
phishing = fetch_ucirepo(id=327)

# Pisahkan fitur (X) dan target (y)
X = phishing.data.features
y = phishing.data.targets.squeeze()  # Konversi ke Series 1D

print(f'Dataset berhasil dimuat dari UCI ML Repository!')
print(f'Shape X: {X.shape}')
print(f'Shape y: {y.shape}')
X.head()

"""## 3. Penyesuaian Kelas Target (2 Kelas: 0 dan 1)

Dataset asli memiliki nilai target: `-1` (Phishing), `0` (Suspicious), `1` (Legitimate).  
Digabung menjadi 2 kelas biner:
- **0** → Phishing (gabungan kelas `-1` dan `0` / Suspicious)
- **1** → Legitimate

Alasan Mengapa dijadiin 2 aja yaitu:
- Sampel kelas suspicious relatif sedikit jadi kurang representatif untuk dilatih sebagai kelas terpisah
- Konteks keamanan jadi website suspicious tetap berpotensi berbahaya, sehingga lebih aman dikategorikan sebagai phishing
- Klasifikasi biner lebih sederhana jadi model lebih stabil dan proses evaluasi lebih mudah
"""

y = y.apply(lambda v: 0 if v <= 0 else 1)

print('Distribusi kelas setelah penyesuaian:')
vc = y.value_counts()
print(f'  Phishing   (0) : {vc[0]:,} ({vc[0]/len(y)*100:.1f}%)')
print(f'  Legitimate (1) : {vc[1]:,} ({vc[1]/len(y)*100:.1f}%)')

"""## 4. Eksplorasi Data (EDA)"""

# Informasi umum dataset sebelum balancing
print('=== INFO DATASET ===')
print(f'Jumlah Fitur   : {X.shape[1]}')
print(f'Jumlah Sampel  : {X.shape[0]:,}')
print(f'Missing Values : {X.isnull().sum().sum()}')

# Visualisasi distribusi kelas dan korelasi fitur dengan target
df_eda = X.copy()
df_eda['Result'] = y.values

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle('Distribusi Dataset (Sebelum Balancing)', fontsize=14, fontweight='bold')

# Pie chart distribusi kelas
colors = ['#e74c3c', '#2ecc71']
labels = ['Phishing (0)', 'Legitimate (1)']
sizes  = [vc[0], vc[1]]
axes[0].pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%',
            startangle=90, wedgeprops={'edgecolor': 'white', 'linewidth': 2})
axes[0].set_title('Distribusi Kelas Target')

# Bar chart korelasi fitur dengan target (top 15)
corr = df_eda.corr()['Result'].drop('Result').abs().sort_values(ascending=True).tail(15)
axes[1].barh(corr.index, corr.values, color=plt.cm.RdYlGn(corr.values), edgecolor='white')
axes[1].set_title('Top 15 Fitur vs Target (|Korelasi|)')
axes[1].set_xlabel('|Korelasi|')
axes[1].set_facecolor('#f9f9f9')

plt.tight_layout()
plt.show()

"""## 5. Balancing Data dengan SMOTE"""

# Terapkan SMOTE untuk menyeimbangkan kelas sebelum splitting
smote = SMOTE(random_state=42)
X_balanced, y_balanced = smote.fit_resample(X, y)

# Tampilkan distribusi kelas setelah balancing
vc_bal = pd.Series(y_balanced).value_counts()
print('Distribusi kelas setelah SMOTE:')
print(f'  Phishing   (0) : {vc_bal[0]:,} ({vc_bal[0]/len(y_balanced)*100:.1f}%)')
print(f'  Legitimate (1) : {vc_bal[1]:,} ({vc_bal[1]/len(y_balanced)*100:.1f}%)')
print(f'Total sampel     : {len(y_balanced):,}')

"""## 6. Preprocessing"""

# Split data 80/20 dengan stratifikasi setelah balancing
X_train, X_test, y_train, y_test = train_test_split(
    X_balanced, y_balanced, test_size=0.2, random_state=42, stratify=y_balanced
)

# Scaling fitur (diperlukan oleh KNN dan SVM)
scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)  # Fit hanya pada data train
X_test_sc  = scaler.transform(X_test)       # Transform data test dengan scaler yang sama

print(f'Data Train : {X_train.shape[0]:,} sampel')
print(f'Data Test  : {X_test.shape[0]:,} sampel')

"""---
# Model 1: Random Forest (RF)

## 7. Training Model Random Forest
"""

# Melatih Random Forest menggunakan data asli (tanpa scaling)
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

# Prediksi label dan probabilitas kelas positif (1 = Legitimate)
y_pred_rf = rf.predict(X_test)
y_prob_rf = rf.predict_proba(X_test)[:, 1]

print('Model Random Forest selesai dilatih!')
print(f'n_estimators : 100')
print(f'random_state : 42')

"""## 8. Evaluasi Model Random Forest"""

# Hitung metrik evaluasi untuk Random Forest
acc_rf  = accuracy_score(y_test, y_pred_rf)
prec_rf = precision_score(y_test, y_pred_rf, pos_label=1)
rec_rf  = recall_score(y_test, y_pred_rf, pos_label=1)
f1_rf   = f1_score(y_test, y_pred_rf, pos_label=1)
auc_rf  = roc_auc_score(y_test, y_prob_rf)

# Cross-validation 5-fold untuk estimasi performa yang lebih stabil
cv_rf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores_rf = cross_val_score(rf, X_train, y_train, cv=cv_rf, scoring='accuracy')

print('HASIL EVALUASI RANDOM FOREST')
print(f'Accuracy  : {acc_rf:.4f} ({acc_rf*100:.2f}%)')
print(f'Precision : {prec_rf:.4f}')
print(f'Recall    : {rec_rf:.4f}')
print(f'F1-Score  : {f1_rf:.4f}')
print(f'AUC-ROC   : {auc_rf:.4f}')
print(f'CV (5-fold): {cv_scores_rf.mean():.4f} +/- {cv_scores_rf.std():.4f}')

# Confusion matrix Random Forest
cm_rf = confusion_matrix(y_test, y_pred_rf)
tn_rf, fp_rf, fn_rf, tp_rf = cm_rf.ravel()

plt.figure(figsize=(7, 6))
sns.heatmap(
    cm_rf, annot=True, fmt='d', cmap='Greens',
    xticklabels=['Phishing (0)', 'Legitimate (1)'],
    yticklabels=['Phishing (0)', 'Legitimate (1)'],
    linewidths=1, linecolor='white',
    annot_kws={'size': 15, 'weight': 'bold'}
)
plt.title(f'Confusion Matrix — Random Forest\nAccuracy: {acc_rf:.4f}', fontweight='bold', fontsize=13)
plt.xlabel(f'Predicted Label\nTP={tp_rf} | TN={tn_rf} | FP={fp_rf} | FN={fn_rf}', fontsize=10)
plt.ylabel('True Label', fontsize=10)
plt.tight_layout()
plt.show()

# ROC Curve Random Forest
fpr_rf, tpr_rf, _ = roc_curve(y_test, y_prob_rf, pos_label=1)

plt.figure(figsize=(8, 6))
plt.plot(fpr_rf, tpr_rf, color='#27ae60', lw=2, label=f'RF (AUC = {auc_rf:.4f})')
plt.plot([0, 1], [0, 1], 'k--', lw=1.5, label='Random Classifier')
plt.fill_between(fpr_rf, tpr_rf, alpha=0.1, color='#27ae60')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.02])
plt.xlabel('False Positive Rate (FPR)', fontsize=12)
plt.ylabel('True Positive Rate (TPR)', fontsize=12)
plt.title('ROC Curve — Random Forest', fontsize=14, fontweight='bold')
plt.legend(loc='lower right', fontsize=11)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Fitur paling berpengaruh dalam keputusan Random Forest (top 10)
importances = rf.feature_importances_
feat_imp = pd.Series(importances, index=X.columns).sort_values(ascending=False)

print('Top 10 Feature Importances:')
print(feat_imp.head(10))

feat_imp.head(10).plot(kind='bar', color='#27ae60', figsize=(10, 5))
plt.title('Top 10 Feature Importance — Random Forest', fontsize=13, fontweight='bold')
plt.xlabel('Fitur')
plt.ylabel('Importance')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Laporan klasifikasi lengkap per kelas
print('CLASSIFICATION REPORT — Random Forest')
print(classification_report(
    y_test, y_pred_rf,
    target_names=['Phishing (0)', 'Legitimate (1)']
))

# Ringkasan hasil Random Forest
print('=' * 48)
print('     RINGKASAN HASIL — Random Forest (RF)    ')
print('=' * 48)
print(f'Accuracy  : {acc_rf:.4f} ({acc_rf*100:.2f}%)')
print(f'Precision : {prec_rf:.4f}')
print(f'Recall    : {rec_rf:.4f}')
print(f'F1-Score  : {f1_rf:.4f}')
print(f'AUC-ROC   : {auc_rf:.4f}')
print(f'CV Mean   : {cv_scores_rf.mean():.4f} +/- {cv_scores_rf.std():.4f}')
print('-' * 48)
print(f'TP : {tp_rf}  |  TN : {tn_rf}')
print(f'FP : {fp_rf}  |  FN : {fn_rf}')
print('=' * 48)

"""---
# Model 2: K-Nearest Neighbors (KNN)

## 9. Mencari Nilai K Optimal
"""

# Mencari nilai K terbaik dengan cross-validation pada data yang sudah di-scale
k_range = range(2, 11)
k_scores = []

for k in k_range:
    knn_tmp = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn_tmp, X_train_sc, y_train, cv=5, scoring='accuracy')
    k_scores.append(scores.mean())
    print(f'K={k:2d} -> CV Accuracy: {scores.mean():.4f}')

# Pilih K dengan akurasi CV tertinggi
best_k = list(k_range)[k_scores.index(max(k_scores))]
print(f'\nK terbaik: {best_k} (Accuracy: {max(k_scores):.4f})')

# Visualisasi perubahan akurasi terhadap nilai K
plt.figure(figsize=(10, 5))
plt.plot(k_range, k_scores, marker='o', color='#3498db', linewidth=2, markersize=7)
plt.axvline(x=best_k, color='#e74c3c', linestyle='--', linewidth=1.5, label=f'K terbaik = {best_k}')
plt.scatter([best_k], [max(k_scores)], color='#e74c3c', s=100, zorder=5)
plt.title('Pemilihan Nilai K Optimal', fontsize=14, fontweight='bold')
plt.xlabel('Nilai K')
plt.ylabel('CV Accuracy')
plt.xticks(k_range)
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""## 10. Training Model KNN"""

# Melatih KNN menggunakan data yang sudah discale dan nilai K terbaik
knn = KNeighborsClassifier(n_neighbors=best_k, weights='uniform', metric='minkowski')
knn.fit(X_train_sc, y_train)

# Prediksi label dan probabilitas kelas positif (1 = Legitimate)
y_pred_knn = knn.predict(X_test_sc)
y_prob_knn = knn.predict_proba(X_test_sc)[:, 1]

print('Model KNN selesai dilatih!')
print(f'K (n_neighbors) : {best_k}')
print(f'Weights         : uniform')
print(f'Metric          : minkowski')

"""## 11. Evaluasi Model KNN"""

# Hitung metrik evaluasi untuk KNN
acc_knn  = accuracy_score(y_test, y_pred_knn)
prec_knn = precision_score(y_test, y_pred_knn, pos_label=1)
rec_knn  = recall_score(y_test, y_pred_knn, pos_label=1)
f1_knn   = f1_score(y_test, y_pred_knn, pos_label=1)
auc_knn  = roc_auc_score(y_test, y_prob_knn)

# Cross-validation 5-fold untuk KNN
cv_knn = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores_knn = cross_val_score(knn, X_train_sc, y_train, cv=cv_knn, scoring='accuracy')

print('HASIL EVALUASI KNN')
print(f'Accuracy  : {acc_knn:.4f} ({acc_knn*100:.2f}%)')
print(f'Precision : {prec_knn:.4f}')
print(f'Recall    : {rec_knn:.4f}')
print(f'F1-Score  : {f1_knn:.4f}')
print(f'AUC-ROC   : {auc_knn:.4f}')
print(f'CV (5-fold): {cv_scores_knn.mean():.4f} +/- {cv_scores_knn.std():.4f}')

# Confusion matrix KNN
cm_knn = confusion_matrix(y_test, y_pred_knn)
tn_knn, fp_knn, fn_knn, tp_knn = cm_knn.ravel()

plt.figure(figsize=(7, 6))
sns.heatmap(
    cm_knn, annot=True, fmt='d', cmap='Blues',
    xticklabels=['Phishing (0)', 'Legitimate (1)'],
    yticklabels=['Phishing (0)', 'Legitimate (1)'],
    linewidths=1, linecolor='white',
    annot_kws={'size': 15, 'weight': 'bold'}
)
plt.title(f'Confusion Matrix — KNN (K={best_k})\nAccuracy: {acc_knn:.4f}', fontweight='bold', fontsize=13)
plt.xlabel(f'Predicted Label\nTP={tp_knn} | TN={tn_knn} | FP={fp_knn} | FN={fn_knn}', fontsize=10)
plt.ylabel('True Label', fontsize=10)
plt.tight_layout()
plt.show()

# ROC Curve KNN
fpr_knn, tpr_knn, _ = roc_curve(y_test, y_prob_knn, pos_label=1)

plt.figure(figsize=(8, 6))
plt.plot(fpr_knn, tpr_knn, color='#3498db', lw=2, label=f'KNN (AUC = {auc_knn:.4f})')
plt.plot([0, 1], [0, 1], 'k--', lw=1.5, label='Random Classifier')
plt.fill_between(fpr_knn, tpr_knn, alpha=0.1, color='#3498db')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.02])
plt.xlabel('False Positive Rate (FPR)', fontsize=12)
plt.ylabel('True Positive Rate (TPR)', fontsize=12)
plt.title(f'ROC Curve — KNN (K={best_k})', fontsize=14, fontweight='bold')
plt.legend(loc='lower right', fontsize=11)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Laporan klasifikasi lengkap per kelas
print('CLASSIFICATION REPORT — KNN')
print(classification_report(
    y_test, y_pred_knn,
    target_names=['Phishing (0)', 'Legitimate (1)']
))

# Ringkasan hasil KNN
print('=' * 45)
print(f'     RINGKASAN HASIL — KNN (K={best_k})    ')
print('=' * 45)
print(f'Accuracy  : {acc_knn:.4f} ({acc_knn*100:.2f}%)')
print(f'Precision : {prec_knn:.4f}')
print(f'Recall    : {rec_knn:.4f}')
print(f'F1-Score  : {f1_knn:.4f}')
print(f'AUC-ROC   : {auc_knn:.4f}')
print(f'CV Mean   : {cv_scores_knn.mean():.4f} +/- {cv_scores_knn.std():.4f}')
print('-' * 45)
print(f'TP : {tp_knn}  |  TN : {tn_knn}')
print(f'FP : {fp_knn}  |  FN : {fn_knn}')
print('=' * 45)

"""---
# Model 3: Support Vector Machine (SVM)

## 12. Training Model SVM
"""

# Melatih SVM dengan kernel RBF menggunakan data yang sudah di-scale
svm = SVC(kernel='rbf', C=1.0, gamma='scale', probability=True, random_state=42)
svm.fit(X_train_sc, y_train)

# Prediksi label dan probabilitas kelas positif (1 = Legitimate)
y_pred_svm = svm.predict(X_test_sc)
y_prob_svm = svm.predict_proba(X_test_sc)[:, 1]

print('Model SVM selesai dilatih!')
print(f'Kernel : RBF')
print(f'C      : 1.0')
print(f'Gamma  : scale')

"""## 13. Evaluasi Model SVM"""

# Hitung metrik evaluasi untuk SVM
acc_svm  = accuracy_score(y_test, y_pred_svm)
prec_svm = precision_score(y_test, y_pred_svm, pos_label=1)
rec_svm  = recall_score(y_test, y_pred_svm, pos_label=1)
f1_svm   = f1_score(y_test, y_pred_svm, pos_label=1)
auc_svm  = roc_auc_score(y_test, y_prob_svm)

# Cross-validation 5-fold untuk SVM
cv_svm = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores_svm = cross_val_score(svm, X_train_sc, y_train, cv=cv_svm, scoring='accuracy')

print('HASIL EVALUASI SVM')
print(f'Accuracy  : {acc_svm:.4f} ({acc_svm*100:.2f}%)')
print(f'Precision : {prec_svm:.4f}')
print(f'Recall    : {rec_svm:.4f}')
print(f'F1-Score  : {f1_svm:.4f}')
print(f'AUC-ROC   : {auc_svm:.4f}')
print(f'CV (5-fold): {cv_scores_svm.mean():.4f} +/- {cv_scores_svm.std():.4f}')

# Confusion matrix SVM
cm_svm = confusion_matrix(y_test, y_pred_svm)
tn_svm, fp_svm, fn_svm, tp_svm = cm_svm.ravel()

plt.figure(figsize=(7, 6))
sns.heatmap(
    cm_svm, annot=True, fmt='d', cmap='Oranges',
    xticklabels=['Phishing (0)', 'Legitimate (1)'],
    yticklabels=['Phishing (0)', 'Legitimate (1)'],
    linewidths=1, linecolor='white',
    annot_kws={'size': 15, 'weight': 'bold'}
)
plt.title(f'Confusion Matrix — SVM (RBF)\nAccuracy: {acc_svm:.4f}', fontweight='bold', fontsize=13)
plt.xlabel(f'Predicted Label\nTP={tp_svm} | TN={tn_svm} | FP={fp_svm} | FN={fn_svm}', fontsize=10)
plt.ylabel('True Label', fontsize=10)
plt.tight_layout()
plt.show()

# ROC Curve SVM
fpr_svm, tpr_svm, _ = roc_curve(y_test, y_prob_svm, pos_label=1)

plt.figure(figsize=(8, 6))
plt.plot(fpr_svm, tpr_svm, color='#e67e22', lw=2, label=f'SVM (AUC = {auc_svm:.4f})')
plt.plot([0, 1], [0, 1], 'k--', lw=1.5, label='Random Classifier')
plt.fill_between(fpr_svm, tpr_svm, alpha=0.1, color='#e67e22')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.02])
plt.xlabel('False Positive Rate (FPR)', fontsize=12)
plt.ylabel('True Positive Rate (TPR)', fontsize=12)
plt.title('ROC Curve — SVM (RBF Kernel)', fontsize=14, fontweight='bold')
plt.legend(loc='lower right', fontsize=11)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Laporan klasifikasi lengkap per kelas
print('CLASSIFICATION REPORT — SVM')
print(classification_report(
    y_test, y_pred_svm,
    target_names=['Phishing (0)', 'Legitimate (1)']
))

# Ringkasan hasil SVM
print('=' * 45)
print('     RINGKASAN HASIL — SVM (RBF Kernel)    ')
print('=' * 45)
print(f'Accuracy  : {acc_svm:.4f} ({acc_svm*100:.2f}%)')
print(f'Precision : {prec_svm:.4f}')
print(f'Recall    : {rec_svm:.4f}')
print(f'F1-Score  : {f1_svm:.4f}')
print(f'AUC-ROC   : {auc_svm:.4f}')
print(f'CV Mean   : {cv_scores_svm.mean():.4f} +/- {cv_scores_svm.std():.4f}')
print('-' * 45)
print(f'TP : {tp_svm}  |  TN : {tn_svm}')
print(f'FP : {fp_svm}  |  FN : {fn_svm}')
print('=' * 45)

"""# MODEL 4: GRADIENT BOOSTING (XGBOOST)

##14. Training Model
"""

# MODEL GRADIENT BOOSTING (XGBOOST)

xgb_model = XGBClassifier(
    n_estimators=150,
    learning_rate=0.1,
    max_depth=5,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='logloss'
)

# Training model
xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)
y_proba = xgb_model.predict_proba(X_test)[:, 1]

"""##15. Evaluasi Model"""

# EVALUASI MODEL

print("\n=== GRADIENT BOOSTING (XGBOOST) ===")

acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc = roc_auc_score(y_test, y_proba)
cv_scores_xgb = cross_val_score(xgb_model, X_train, y_train, cv=5)

print(f"Accuracy  : {acc:.4f}")
print(f"Precision : {prec:.4f}")
print(f"Recall    : {rec:.4f}")
print(f"F1-Score  : {f1:.4f}")
print(f"ROC-AUC   : {roc:.4f}")
print(f'CV Score : {cv_scores_xgb.mean():.4f} +/- {cv_scores_xgb.std():.4f}')

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

# CONFUSION MATRIX

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix - XGBoost")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# ROC CURVE

fpr, tpr, _ = roc_curve(y_test, y_proba)
fpr_xgb, tpr_xgb, thresholds_xgb = roc_curve(y_test, y_proba)
plt.figure()
plt.plot(fpr, tpr, label=f"XGBoost (AUC = {roc:.4f})")
plt.plot([0,1], [0,1], linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Gradient Boosting")
plt.legend()
plt.show()

# VISUALISASI FITUR PENTING

plt.figure(figsize=(10, 8))


xgb.plot_importance(xgb_model, max_num_features=10, importance_type='weight')

plt.title("10 Fitur Paling Berpengaruh dalam Deteksi Phishing (XGBoost)")
plt.show()

# Ringkasan hasil XGBoost
print('=' * 45)
print('     RINGKASAN HASIL — XGBOOST          ')
print('=' * 45)
print(f'Accuracy  : {acc:.4f} ({acc*100:.2f}%)')
print(f'Precision : {prec:.4f}')
print(f'Recall    : {rec:.4f}')
print(f'F1-Score  : {f1:.4f}')
print(f'AUC-ROC   : {roc:.4f}')
print(f'CV Mean   : {cv_scores_xgb.mean():.4f} +/- {cv_scores_xgb.std():.4f}')
print('-' * 45)


from sklearn.metrics import confusion_matrix
tn_xgb, fp_xgb, fn_xgb, tp_xgb = confusion_matrix(y_test, y_pred).ravel()

print(f'TP : {tp_xgb}  |  TN : {tn_xgb}')
print(f'FP : {fp_xgb}  |  FN : {fn_xgb}')
print('=' * 45)

"""---
# Perbandingan Keempat Model
"""

# Buat tabel perbandingan metrik dari semua model
results = pd.DataFrame({
    'Model'    : ['Random Forest', f'KNN (K={best_k})', 'SVM (RBF)', 'XGBoost'],
    'Accuracy' : [acc_rf,  acc_knn,  acc_svm,  acc],
    'Precision': [prec_rf, prec_knn, prec_svm, prec],
    'Recall'   : [rec_rf,  rec_knn,  rec_svm,  rec],
    'F1-Score' : [f1_rf,   f1_knn,   f1_svm,   f1],
    'AUC-ROC'  : [auc_rf,  auc_knn,  auc_svm,  roc],
    'CV Mean'  : [cv_scores_rf.mean(), cv_scores_knn.mean(), cv_scores_svm.mean(), cv_scores_xgb.mean()]
})

results = results.set_index('Model')

print('PERBANDINGAN 4 MODEL')
print(results.to_string(float_format='{:.4f}'.format))

# Visualisasi perbandingan: bar chart metrik dan ROC curve gabungan
fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Perbandingan Performa Model', fontsize=15, fontweight='bold')

# =========================
# BAR CHART PERBANDINGAN
# =========================
metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'AUC-ROC']
x = np.arange(len(metrics))
width = 0.2

colors_bar = ['#27ae60', '#3498db', '#e67e22', '#9b59b6']

model_labels = [
    'RF',
    f'KNN(K={best_k})',
    'SVM',
    'XGBoost'
]

model_values = [
    [acc_rf, prec_rf, rec_rf, f1_rf, auc_rf],
    [acc_knn, prec_knn, rec_knn, f1_knn, auc_knn],
    [acc_svm, prec_svm, rec_svm, f1_svm, auc_svm],
    [acc, prec, rec, f1, roc]
]

for i, (vals, color, label) in enumerate(zip(model_values, colors_bar, model_labels)):
    axes[0].bar(
        x + i * width,
        vals,
        width,
        label=label,
        color=color,
        alpha=0.85
    )

axes[0].set_xticks(x + width * 1.5)
axes[0].set_xticklabels(metrics, rotation=15)
axes[0].set_ylabel('Score')
axes[0].set_ylim([0.85, 1.01])
axes[0].set_title('Metrik Perbandingan')
axes[0].legend()
axes[0].grid(True, axis='y', alpha=0.3)

# =========================
# ROC CURVE GABUNGAN
# =========================
axes[1].plot(
    fpr_rf, tpr_rf,
    color='#27ae60',
    lw=2,
    label=f'RF (AUC={auc_rf:.4f})'
)

axes[1].plot(
    fpr_knn, tpr_knn,
    color='#3498db',
    lw=2,
    label=f'KNN (AUC={auc_knn:.4f})'
)

axes[1].plot(
    fpr_svm, tpr_svm,
    color='#e67e22',
    lw=2,
    label=f'SVM (AUC={auc_svm:.4f})'
)

axes[1].plot(
    fpr_xgb, tpr_xgb,
    color='#9b59b6',
    lw=2,
    label=f'XGBoost (AUC={roc:.4f})'
)

axes[1].plot(
    [0, 1],
    [0, 1],
    'k--',
    lw=1.5,
    label='Random Classifier'
)

axes[1].set_xlabel('False Positive Rate')
axes[1].set_ylabel('True Positive Rate')
axes[1].set_title('ROC Curve Gabungan')
axes[1].legend(loc='lower right')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()